### PR TITLE
Clear store data on map entry & fixes Toksook lat / lon 

### LINKED ISSUE #74: Named points from dropdown menu return "no data".
Places in our dropdown menu are returning "no data". The points we chose should all have data.

As of July 3rd at 1430 Tooksook Bay is the only one I test that returns this null result.

### PR DESCRIPTION
**Pull request by BobTorgerson**
This PR adds a step to clear the report data after the Map component has been mounted. This prevents the possibility of going into a community, clicking either the back button on the browser, or the back button in the application and then clicking on a point on the map and still seeing the name of the community shown.

Additionally, this PR fixes the lat / lon of the Toksook, Alaska community to the nearest available pixel with data. 

Closes #74

### CODE REVIEW

File: src/components/Map.vue [hunk 1]
```diff
@@ -59,6 +59,10 @@ onMounted(() => {
   }).addTo(map)
   updateAtlas()
   map.invalidateSize()
+
+  // This ensures that when the map is shown, it will clear the previous report data
+  // including community name, lat, lon, and data.
+  atlasStore.clearReport()
```
Comment (brucecrevensten) [inline src/components/Map.vue:65]: Could we actually move this to an `unmount()` hook in the `Report` component?  It feels more self-contained there.

**Review by brucecrevensten — CHANGES_REQUESTED** [review]

**Review by brucecrevensten — APPROVED** [review]
